/*
* generated by Xtext
*/
package org.eclipse.xtext.demo.archdsl.language.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class adslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
