/*
 * generated by Xtext
 */
package org.eclipse.xtext.demo.archdsl.language;

/**
 * Use this class to register components to be used within the IDE.
 */
public class adslRuntimeModule extends org.eclipse.xtext.demo.archdsl.language.AbstractadslRuntimeModule {

}
