/*
* generated by Xtext
*/
package org.openarchitectureware.demo.archdsl.language.outline;

import org.eclipse.xtext.ui.common.editor.outline.ContentOutlineNode;
import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;
import org.openarchitectureware.demo.archdsl.language.adsl.File;
import org.openarchitectureware.demo.archdsl.language.adsl.InstanceRef;

/**
 * customization of the default outline structure
 * 
 */
public class AdslTransformer extends AbstractDeclarativeSemanticModelTransformer {
  
  public ContentOutlineNode createNode(
    File semanticNode, ContentOutlineNode parentNode) {
    return super.HIDDEN_NODE; 
  }
  
  public ContentOutlineNode createNode(
		  InstanceRef semanticNode, ContentOutlineNode parentNode) {
		    return super.HIDDEN_NODE; 
		  }
	
}
