/*
 * generated by Xtext
 */
package org.openarchitectureware.demo.archdsl.language;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AdslRuntimeModule extends org.openarchitectureware.demo.archdsl.language.AbstractAdslRuntimeModule {

}
