/*
 * generated by Xtext
 */
package org.eclipse.xtext.demo.archdsl.language;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AdslUiModule extends org.eclipse.xtext.demo.archdsl.language.AbstractAdslUiModule {

}
