/*
 * generated by Xtext
 */
package org.openarchitectureware.var.features;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FeaturesUiModule extends org.openarchitectureware.var.features.AbstractFeaturesUiModule {

}
