/*
* generated by Xtext
*/
package org.eclipse.xtext.demo.archdsl.language.contentassist;

import org.eclipse.xtext.demo.archdsl.language.contentassist.AbstractAdslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AdslProposalProvider extends AbstractAdslProposalProvider {

}
