<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adsl"
    nsURI="http://msg.com/ipot/adsl" nsPrefix="adsl">
  <eClassifiers xsi:type="ecore:EClass" name="File">
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureModel" ordered="false"
        eType="#//FeatureModelImport" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositions" ordered="false"
        upperBound="-1" eType="#//Composition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" ordered="false"
        upperBound="-1" eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partialComponents" ordered="false"
        upperBound="-1" eType="#//PartialComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PartialComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" ordered="false"
        upperBound="-1" eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usings" ordered="false"
        upperBound="-1" eType="#//Using" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" ordered="false"
        upperBound="-1" eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPartialComponents" ordered="false"
        upperBound="-1" eType="#//PartialComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" ordered="false"
        upperBound="-1" eType="#//ComplexType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Using">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partialComponent" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" ordered="false"
        eType="#//ModuleConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureClause" ordered="false"
        eType="#//FeatureClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" ordered="false"
        upperBound="-1" eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isToMany" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" ordered="false"
        unique="false" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMandatory" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" ordered="false"
        upperBound="-1" eType="#//Operation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureClause" ordered="false"
        eType="#//FeatureClause" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultRef" ordered="false"
        eType="#//AnyTypeRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVoid" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false"
        upperBound="-1" eType="#//OperationParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeref" ordered="false"
        eType="#//AnyTypeRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" ordered="false"
        upperBound="-1" eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends" ordered="false"
        eType="#//AnyTypeRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" ordered="false"
        upperBound="-1" eType="#//Operation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasSupertype" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//DataType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureClause" ordered="false"
        eType="#//FeatureClause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeComplex" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isComposite" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReference" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeref" ordered="false"
        eType="#//AnyTypeRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRequired" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributePrimitive" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false"
        eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnyTypeRef" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" unique="false"
        eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleTypeRef" eSuperTypes="#//AnyTypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionTypeRef" eSuperTypes="#//AnyTypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="Composition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" ordered="false"
        upperBound="-1" eType="#//Instance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" ordered="false"
        upperBound="-1" eType="#//Connector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configuration" ordered="false"
        eType="#//InstanceConfiguration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" unique="false"
        eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
        eType="#//InstancePortPair" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
        eType="#//InstancePortPair" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstancePortPair">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" ordered="false" unique="false"
        eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instance" ordered="false"
        unique="false" eType="#//Instance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" ordered="false"
        upperBound="-1" eType="#//ConfigurationParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueTime" ordered="false"
        unique="false" eType="#//ValueTimeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false"
        eType="#//ConfigParamTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="settings" ordered="false"
        upperBound="-1" eType="#//ConfigurationParameterSetting" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationParameterSetting">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        eType="#//ConfigurationParameterValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" ordered="false"
        unique="false" eType="#//ConfigurationParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationParameterValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericConfigurationParameterValue"
      eSuperTypes="#//ConfigurationParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextConfigurationParameterValue" eSuperTypes="#//ConfigurationParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanConfigurationParameterValue"
      eSuperTypes="#//ConfigurationParameterValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" ordered="false"
        eType="#//BooleanLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrueLiteral" eSuperTypes="#//BooleanLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="FalseLiteral" eSuperTypes="#//BooleanLiteral"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureClause" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureAndList" eSuperTypes="#//FeatureClause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureList" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureOrList" eSuperTypes="#//FeatureClause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureList" ordered="false"
        unique="false" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureExpression" eSuperTypes="#//FeatureClause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        eType="#//OrExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//FeatureClause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" ordered="false"
        upperBound="-1" eType="#//AndExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" ordered="false"
        upperBound="-1" eType="#//Operand" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operand">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        eType="#//Atom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNot" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" ordered="false"
        eType="#//OrExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModelImport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="NULL" value="1"/>
    <eLiterals name="int" value="1"/>
    <eLiterals name="char" value="2"/>
    <eLiterals name="string" value="3"/>
    <eLiterals name="short" value="4"/>
    <eLiterals name="date" value="5"/>
    <eLiterals name="boolean" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConfigParamTypeEnum">
    <eLiterals name="NULL" value="1"/>
    <eLiterals name="NUMBER" value="1"/>
    <eLiterals name="TEXT" value="2"/>
    <eLiterals name="BOOL" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ValueTimeEnum">
    <eLiterals name="NULL" value="1"/>
    <eLiterals name="NEVER" value="1"/>
    <eLiterals name="INSTANCEDEFINITION" value="2"/>
    <eLiterals name="DEPLOYMENT" value="3"/>
    <eLiterals name="STARTUP" value="4"/>
  </eClassifiers>
</ecore:EPackage>
