/*
* generated by Xtext
*/
package org.openarchitectureware.var.features.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.eclipse.xtext.parser.antlr.ITokenDefProvider;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import org.openarchitectureware.var.features.services.FeaturesGrammarAccess;

public class FeaturesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject 
    protected ITokenDefProvider antlrTokenDefProvider;
	
	@Inject
	private FeaturesGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		org.openarchitectureware.var.features.parser.antlr.internal.InternalFeaturesLexer lexer = new org.openarchitectureware.var.features.parser.antlr.internal.InternalFeaturesLexer(in);
		XtextTokenStream stream = new XtextTokenStream(lexer, antlrTokenDefProvider);
		stream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		org.openarchitectureware.var.features.parser.antlr.internal.InternalFeaturesParser parser = new org.openarchitectureware.var.features.parser.antlr.internal.InternalFeaturesParser(
				stream, getElementFactory(), grammarAccess);
		parser.setTokenTypeMap(antlrTokenDefProvider.getTokenDefMap());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "FeatureClause";
	}
	
	public FeaturesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FeaturesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
