/*
* generated by Xtext
*/
package org.eclipse.xtext.demo.archdsl.language.contentassist;

import org.eclipse.xtext.demo.archdsl.language.contentassist.AbstractadslProposalProvider;
/**
 * see http://wiki.eclipse.org/Xtext/Documentation#Content_Assist on how to customize content assistant
 */
public class adslProposalProvider extends AbstractadslProposalProvider {

}
