/*
 * generated by Xtext
 */
package org.openarchitectureware.demo.archdsl.language.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class AdslFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		org.openarchitectureware.demo.archdsl.language.services.AdslGrammarAccess f = (org.openarchitectureware.demo.archdsl.language.services.AdslGrammarAccess) getGrammarAccess();

		//...
	}
}
