/*
 * generated by Xtext
 */
package org.eclipse.xtext.demo.archdsl.language.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://wiki.eclipse.org/Xtext/Documentation#Formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class adslFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		org.eclipse.xtext.demo.archdsl.language.services.adslGrammarAccess f = (org.eclipse.xtext.demo.archdsl.language.services.adslGrammarAccess) getGrammarAccess();

		//...
	}
}
