/*
* generated by Xtext
*/
package org.eclipse.xtext.demo.archdsl.language.labeling;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.core.DefaultLabelProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class AdslLabelProvider extends DefaultLabelProvider {
/*
	
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
	 
*/
  
    String image( EObject ele ){
      return ele.eClass().getName().toLowerCase()+".gif";
    }
  
}
