/*
* generated by Xtext
*/
package org.openarchitectureware.var.features.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FeaturesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/openarchitectureware/var/features/parser/antlr/internal/InternalFeatures.tokens");
	}
}
